apiVersion: apps/v1
kind: Deployment
metadata:
  name: malicious-text-system
spec:
  selector:
    matchLabels:
      app: malicious-text-system
  replicas: 1
  template:
    metadata:
      labels:
        app: malicious-text-system
    spec:
      containers:
        - name: malicious-text-system
          image: kodkod1docker/malicious-text-system:v12
          ports:
            - containerPort: 8085
              protocol: TCP
          env: 
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: malicious-text-system-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: malicious-text-system-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: malicious-text-system-secret
                  key: MONGO_INITDB_CLUSTER
            - name: MONGO_COLLECTION
              valueFrom:
                secretKeyRef:
                  name: malicious-text-system-secret
                  key: MONGO_COLLECTION
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
      restartPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%