apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: malicious-text-system
  labels:
    app: malicious-text-system
spec:
  to:
    name: malicious-text-system
    weight: 100
    kind: Service
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
